# Generated by Django 2.0.13 on 2021-06-01 08:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promocodes', '0001_initial'),
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('tracking_client_id', models.CharField(blank=True, editable=False, max_length=36)),
                ('user_email', models.EmailField(blank=True, default='', editable=False, max_length=254)),
                ('shipping_price_net', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('shipping_price_gross', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12)),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('token', models.CharField(max_length=36, unique=True)),
                ('total_net', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_gross', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('discount_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('canceled', 'Canceled'), ('on hold', 'On hold'), ('shipped', 'Shipped'), ('test', 'Test'), ('pre order', 'Pre-order'), ('one click', 'One click'), ('no answer', 'No answer'), ('send to dealer', 'Send to dealer'), ('no answer', 'No answer'), ('call back request', 'Call Back Request')], default='open', max_length=128)),
                ('tracking_number', models.CharField(blank=True, default='', max_length=255)),
                ('pre_order_user_phone', models.CharField(blank=True, default='', max_length=20)),
                ('promocode_saved_money', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('nip', models.CharField(default='', max_length=255)),
                ('promocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='promocodes.Promocode')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=128)),
                ('is_shipping_required', models.BooleanField()),
                ('stock_location', models.CharField(default='', max_length=100)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('unit_price_net', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unit_price_gross', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='product.ProductVariant')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.Stock')),
            ],
        ),
    ]
