# Generated by Django 2.0.13 on 2021-06-01 08:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('value', models.TextField(blank=True)),
                ('lang', models.CharField(max_length=12)),
                ('order', models.PositiveIntegerField(default=0)),
                ('show_tag', models.BooleanField(default=False)),
                ('gradient', models.TextField(blank=True, default='')),
                ('tag_text_color', models.CharField(choices=[('#ffffff', 'White text'), ('#000000', 'Black text')], default='#000000', max_length=30)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('fixed', 'Fixed amount from base price'), ('percentage', 'Amount - % from base price')], default=('fixed', 'Fixed amount from base price'), max_length=10)),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateField(default=datetime.date.today)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('priority', models.SmallIntegerField(default=0)),
                ('name_display', models.ForeignKey(default=None, help_text='Displayed in checkout', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sale.DiscountName')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='product.ProductVariant')),
            ],
            options={
                'permissions': (('view_sale', 'Can view sales'), ('edit_sale', 'Can edit sales')),
            },
        ),
    ]
