# Generated by Django 2.0.13 on 2021-06-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discountname',
            name='lang',
        ),
    ]
