# Generated by Django 2.0.13 on 2021-06-02 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0002_remove_discountname_lang'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discountname',
            options={'ordering': ['order'], 'verbose_name': 'Sale Name'},
        ),
    ]
