# Generated by Django 2.0.13 on 2021-06-01 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(blank=True, default='', max_length=255)),
                ('type', models.PositiveSmallIntegerField(choices=[(0, 'Percent'), (1, 'Absolute'), (2, 'Free shipping')], default=0)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('code_variants', models.TextField(blank=True, default='', help_text='Split words by comma. Example: Test, TEST, test')),
                ('lang', models.CharField(max_length=12)),
                ('usage_count', models.PositiveIntegerField(blank=True, default=0)),
                ('min_order_sum', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12)),
                ('exclude_active_sales_products', models.BooleanField(default=False)),
                ('exclude_show_in_discounts_products', models.BooleanField(default=False)),
                ('from_base_price', models.BooleanField(default=False)),
                ('categories', models.ManyToManyField(blank=True, related_name='promocodes', to='product.Category')),
                ('categories_for_exclude', models.ManyToManyField(blank=True, related_name='exclude_promocodes', to='product.Category')),
                ('products', models.ManyToManyField(blank=True, related_name='promocodes', to='product.ProductVariant')),
                ('products_for_exclude', models.ManyToManyField(blank=True, related_name='exclude_promocodes', to='product.ProductVariant')),
                ('users', models.ManyToManyField(blank=True, related_name='promocodes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PromocodeUsage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('promocode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='promocodes.Promocode')),
            ],
        ),
    ]
