# Generated by Django 2.0.13 on 2021-06-01 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
        ('promocodes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocodeusage',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='promocode_usages', to='order.Order'),
            preserve_default=False,
        ),
    ]
