# Generated by Django 2.0.13 on 2021-06-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartline',
            name='data',
            field=models.TextField(blank=True),
        ),
    ]
