# Generated by Django 2.0.13 on 2021-06-01 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210601_1808'),
        ('cart', '0002_cartline_data'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartline',
            unique_together={('cart', 'variant', 'data')},
        ),
    ]
