# Generated by Django 2.0.13 on 2021-06-01 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='promo_cover',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='add_default',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='alt_category',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='attr_show',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='registration_block',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='seo_description',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='seo_keywords',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='seo_title',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='teaser_desc',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='use_alt_category',
        ),
    ]
