# Generated by Django 2.0.13 on 2021-06-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20210601_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'permissions': (('view_category', 'Can view categories'), ('edit_category', 'Can edit categories'), ('view_sku_global', 'Can view SKU'), ('edit_sku_global', 'Can edit SKU')), 'verbose_name': 'Category'},
        ),
    ]
