# Generated by Django 2.0.13 on 2021-06-02 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20210602_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'Product'},
        ),
    ]
